# Generated by Django 5.0.1 on 2024-02-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Фотография '),
        ),
    ]
